"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def even_fibonacci_numbers(n):
    res = 0
    last = 1
    current = 2

    while current < n:
        if current % 2 == 0:
            res += current
        
        new = current + last
        last = current
        current = new

    return res

if __name__ == '__main__':
    print(even_fibonacci_numbers(4000000))